In [1]:
import pandas as pd
from pathlib import Path

In [6]:
train_path = "../dataset/annotations/EPIC_100_train.csv"
val_path = "../dataset/annotations/EPIC_100_validation.csv"
verb_path = "../dataset/annotations/EPIC_100_verb_classes.csv"
noun_path = "../dataset/annotations/EPIC_100_noun_classes.csv"
video_info_path = "../dataset/annotations/EPIC_100_video_info.csv"

In [7]:
train_df = pd.read_csv(train_path)
val_df = pd.read_csv(val_path)

verb_df = pd.read_csv(verb_path)
noun_df = pd.read_csv(noun_path)
video_df = pd.read_csv(video_info_path)

In [8]:
print("Training samples:", len(train_df))
print("Validation samples:", len(val_df))

print("\nColumns:\n")
print(train_df.columns.tolist())

Training samples: 67217
Validation samples: 9668

Columns:

['narration_id', 'participant_id', 'video_id', 'narration_timestamp', 'start_timestamp', 'stop_timestamp', 'start_frame', 'stop_frame', 'narration', 'verb', 'verb_class', 'noun', 'noun_class', 'all_nouns', 'all_noun_classes']

In [9]:
train_df.head()

,narration_id,participant_id,video_id,narration_timestamp,start_timestamp,stop_timestamp,start_frame,stop_frame,narration,verb,verb_class,noun,noun_class,all_nouns,all_noun_classes
0,P01_01_0,P01,P01_01,00:01.1,00:00.1,00:03.4,8,202,open door,open,3,door,3,['door'],[3]
1,P01_01_1,P01,P01_01,00:02.6,00:04.4,00:06.2,262,370,turn on light,turn-on,6,light,114,['light'],[114]
2,P01_01_10,P01,P01_01,00:23.3,00:25.0,00:26.2,1498,1572,open drawer,open,3,drawer,8,['drawer'],[8]
3,P01_01_100,P01,P01_01,07:57.9,07:59.8,08:00.9,28785,28852,take cup,take,0,cup,13,['cup'],[13]
4,P01_01_101,P01,P01_01,08:00.0,08:01.5,08:02.2,28888,28932,open cupboard,open,3,cupboard,3,['cupboard'],[3]

In [10]:
train_df.sample(5)

,narration_id,participant_id,video_id,narration_timestamp,start_timestamp,stop_timestamp,start_frame,stop_frame,narration,verb,verb_class,noun,noun_class,all_nouns,all_noun_classes
3061,P01_106_15,P01,P01_106,00:30.6,00:28.0,00:31.0,1398,1549,put down container,put-down,1,container,21,['container'],[21]
58349,P29_03_173,P29,P29_03,10:00.0,09:57.9,10:01.5,35872,36087,throw away,throw,13,rubbish,54,['rubbish'],[54]
15831,P03_28_14,P03,P03_28,00:26.6,00:24.8,00:25.8,1489,1548,pick up bottle,pick-up,0,bottle,15,['bottle'],[15]
37986,P22_08_281,P22,P22_08,11:41.3,11:39.9,11:40.6,41992,42037,rinse hand,rinse,2,hand,11,['hand'],[11]
63509,P31_05_54,P31,P31_05,07:40.1,07:40.4,07:49.7,27625,28181,mix water,mix,10,water,27,['water'],[27]

In [11]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67217 entries, 0 to 67216
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   narration_id         67217 non-null  object
 1   participant_id       67217 non-null  object
 2   video_id             67217 non-null  object
 3   narration_timestamp  67100 non-null  object
 4   start_timestamp      67217 non-null  object
 5   stop_timestamp       67217 non-null  object
 6   start_frame          67217 non-null  int64
 7   stop_frame           67217 non-null  int64
 8   narration            67217 non-null  object
 9   verb                 67217 non-null  object
 10  verb_class           67217 non-null  int64
 11  noun                 67217 non-null  object
 12  noun_class           67217 non-null  int64
 13  all_nouns            67217 non-null  object
 14  all_noun_classes     67217 non-null  object
dtypes: int64(4), object(11)
memory usage: 7.7+ MB

In [12]:
train_df.isnull().sum()

narration_id             0
participant_id           0
video_id                 0
narration_timestamp    117
start_timestamp          0
stop_timestamp           0
start_frame              0
stop_frame               0
narration                0
verb                     0
verb_class               0
noun                     0
noun_class               0
all_nouns                0
all_noun_classes         0
dtype: int64

In [13]:
print("Unique verbs:", train_df["verb"].nunique())

Unique verbs: 856

In [14]:
print("Unique nouns:", train_df["noun"].nunique())

Unique nouns: 2032

In [15]:
train_df["verb"].value_counts().head(30)

verb
pick-up      9868
put-down     7726
open         4851
close        3463
take         3412
rinse        2778
turn-on      2187
put          2106
wash         2078
put-in       2035
turn-off     1806
move         1479
put-on       1164
stir         1123
cut           830
dry           710
put-into      682
clean         657
pour          655
grab          643
lather        598
get           586
shake         527
place         504
throw         501
pour-into     439
remove        393
wipe          359
adjust        353
chop          349
Name: count, dtype: int64

In [16]:
train_df["noun"].value_counts().head(30)

noun
tap               3567
plate             2186
knife             2092
spoon             1806
cupboard          1786
drawer            1590
glass             1526
sponge            1500
pan               1438
lid               1412
hand              1401
bowl              1335
fridge            1149
fork              1074
onion              860
cloth              828
spatula            824
container          758
dough              743
meat               681
water              631
bottle             618
pot                607
bag                538
salt               524
saucepan           521
mug                505
board:chopping     458
cup                421
kettle             412
Name: count, dtype: int64

In [17]:
(
    train_df
    .groupby(["verb", "noun"])
    .size()
    .sort_values(ascending=False)
    .head(50)
)

verb      noun
turn-on   tap          1776
turn-off  tap          1572
open      cupboard     1046
          drawer        920
close     cupboard      703
open      fridge        630
close     drawer        623
pick-up   knife         505
close     fridge        488
pick-up   plate         466
          spoon         458
put-down  plate         447
          knife         435
dry       hand          421
put-down  glass         400
pick-up   glass         394
put-down  spoon         378
pick-up   sponge        374
rinse     hand          319
wash      hand          313
pick-up   bowl          306
          lid           297
rinse     sponge        297
put-down  sponge        292
          lid           283
          fork          273
          bowl          236
pick-up   cloth         236
put-down  cloth         233
          spatula       229
pick-up   pan           224
          spatula       220
put-down  pan           207
open      door          205
rinse     plate         203
take      fork          203
          plate         198
          knife         195
stir      food          186
wash      knife         171
put-down  container     170
pick-up   fork          168
take      spoon         164
pick-up   container     163
shake     hand          156
wash      plate         156
put       plate         153
rinse     knife         150
          glass         149
close     door          146
dtype: int64

In [18]:
def search_by_verb(verb):
    return train_df[train_df["verb"].str.lower() == verb.lower()]

In [19]:
search_by_verb("cut").head()

,narration_id,participant_id,video_id,narration_timestamp,start_timestamp,stop_timestamp,start_frame,stop_frame,narration,verb,verb_class,noun,noun_class,all_nouns,all_noun_classes
33,P01_01_129,P01,P01_01,09:23.3,09:24.2,09:28.8,33855,34130,cut carrots,cut,7,carrot,41,['carrot'],[41]
101,P01_01_190,P01,P01_01,14:31.8,14:30.9,14:35.1,52252,52506,cut tofu sleeve,cut,7,tofu,81,['tofu'],[81]
260,P01_01_37,P01,P01_01,01:44.6,01:45.7,02:02.0,6341,7321,cut courgette,cut,7,courgette,76,['courgette'],[76]
262,P01_01_39,P01,P01_01,02:05.5,02:07.8,02:24.9,7668,8693,cut courgette,cut,7,courgette,76,['courgette'],[76]
264,P01_01_40,P01,P01_01,02:17.5,02:11.0,02:25.8,7859,8747,still cutting courgette,cut,7,courgette,76,['courgette'],[76]

In [20]:
def search_narration(keyword):
    return train_df[
        train_df["narration"].str.contains(
            keyword,
            case=False,
            na=False
        )
    ]

In [21]:
search_narration("onion")

,narration_id,participant_id,video_id,narration_timestamp,start_timestamp,stop_timestamp,start_frame,stop_frame,narration,verb,verb_class,noun,noun_class,all_nouns,all_noun_classes
62,P01_01_155,P01,P01_01,11:57.8,11:59.0,12:00.0,43141,43202,take cutting board with onion,take,0,board:cutting,18,"['board:cutting', 'onion']","[18, 16]"
63,P01_01_156,P01,P01_01,11:59.2,12:00.5,12:02.4,43227,43342,pouring onion,pour,9,onion,16,['onion'],[16]
303,P01_01_76,P01,P01_01,06:22.8,06:21.5,06:24.9,22891,23091,take onion,take,0,onion,16,['onion'],[16]
304,P01_01_77,P01,P01_01,06:20.1,06:24.0,06:24.8,23040,23085,take onion,take,0,onion,16,['onion'],[16]
305,P01_01_78,P01,P01_01,06:23.8,06:24.9,06:25.6,23091,23134,put down onion,put-down,1,onion,16,['onion'],[16]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66910,P37_101_364,P37,P37_101,26:23.7,26:10.4,27:34.1,78520,82706,chop onions,chop,7,onion,16,['onion'],[16]
66917,P37_101_370,P37,P37_101,27:43.3,27:41.7,27:44.3,83082,83216,shovel up onions,shovel-up,16,onion,16,['onion'],[16]
66918,P37_101_371,P37,P37_101,27:44.4,27:44.2,27:46.6,83211,83332,put onions in bowl,put-in,5,onion,16,"['onion', 'bowl']","[16, 7]"
66919,P37_101_372,P37,P37_101,27:48.4,27:47.8,27:49.3,83389,83466,shovel up onions,shovel-up,16,onion,16,['onion'],[16]
66920,P37_101_373,P37,P37_101,27:49.9,27:49.4,27:51.6,83471,83578,put onions in bowl,put-in,5,onion,16,"['onion', 'bowl']","[16, 7]"

In [22]:
verb_counts = (
    train_df["verb"]
    .value_counts()
    .reset_index()
)

verb_counts.columns = ["Verb", "Count"]

verb_counts.head(50)

           Verb  Count
0       pick-up   9868
1      put-down   7726
2          open   4851
3         close   3463
4          take   3412
5         rinse   2778
6       turn-on   2187
7           put   2106
8          wash   2078
9        put-in   2035
10     turn-off   1806
11         move   1479
12       put-on   1164
13         stir   1123
14          cut    830
15          dry    710
16     put-into    682
17        clean    657
18         pour    655
19         grab    643
20       lather    598
21          get    586
22        shake    527
23        place    504
24        throw    501
25    pour-into    439
26       remove    393
27         wipe    359
28       adjust    353
29         chop    349
30        slice    324
31        empty    304
32         peel    302
33     take-out    295
34      squeeze    269
35          mix    212
36         turn    210
37         flip    196
38         fold    173
39     put-onto    171
40     place-on    164
41        press    157
42    take-from    154
43        scrub    149
44     take-off    147
45      pour-in    147
46    pour-from    144
47        check    143
48  remove-from    143
49         hold    141

In [23]:
noun_counts = (
    train_df["noun"]
    .value_counts()
    .reset_index()
)

noun_counts.columns = ["Noun", "Count"]

noun_counts.head(50)

              Noun  Count
0              tap   3567
1            plate   2186
2            knife   2092
3            spoon   1806
4         cupboard   1786
5           drawer   1590
6            glass   1526
7           sponge   1500
8              pan   1438
9              lid   1412
10            hand   1401
11            bowl   1335
12          fridge   1149
13            fork   1074
14           onion    860
15           cloth    828
16         spatula    824
17       container    758
18           dough    743
19            meat    681
20           water    631
21          bottle    618
22             pot    607
23             bag    538
24            salt    524
25        saucepan    521
26             mug    505
27  board:chopping    458
28             cup    421
29          kettle    412
30             oil    395
31   board:cutting    392
32            food    386
33          cheese    380
34             egg    375
35           pasta    373
36          potato    364
37          carrot    362
38            door    356
39             hob    354
40        colander    347
41          tomato    311
42          garlic    311
43             jar    308
44      tupperware    302
45            rice    293
46            oven    291
47             bin    280
48         cutlery    272
49            sink    269

In [24]:
train_df.iloc[0]

narration_id            P01_01_0
participant_id               P01
video_id                  P01_01
narration_timestamp      00:01.1
start_timestamp          00:00.1
stop_timestamp           00:03.4
start_frame                    8
stop_frame                   202
narration              open door
verb                        open
verb_class                     3
noun                        door
noun_class                     3
all_nouns               ['door']
all_noun_classes             [3]
Name: 0, dtype: object

In [25]:
cut_df = search_by_verb("cut")

cut_df[
    [
        "video_id",
        "participant_id",
        "start_timestamp",
        "stop_timestamp",
        "narration",
        "verb",
        "noun"
    ]
].head(20)

,video_id,participant_id,start_timestamp,stop_timestamp,narration,verb,noun
33,P01_01,P01,09:24.2,09:28.8,cut carrots,cut,carrot
101,P01_01,P01,14:30.9,14:35.1,cut tofu sleeve,cut,tofu
260,P01_01,P01,01:45.7,02:02.0,cut courgette,cut,courgette
262,P01_01,P01,02:07.8,02:24.9,cut courgette,cut,courgette
264,P01_01,P01,02:11.0,02:25.8,still cutting courgette,cut,courgette
289,P01_01,P01,05:22.8,05:28.2,cut celery,cut,celery
290,P01_01,P01,05:28.3,05:38.1,still cutting celery,cut,celery
310,P01_01,P01,06:32.6,06:38.8,cut onion,cut,onion
311,P01_01,P01,06:35.4,06:47.0,still cutting onion,cut,onion
312,P01_01,P01,06:48.4,07:02.2,still cutting onion,cut,onion
1158,P01_09,P01,18:03.9,18:10.6,cut onion,cut,onion
1160,P01_09,P01,18:14.1,18:16.8,cut onion,cut,onion
1166,P01_09,P01,18:25.6,18:28.2,cut onion,cut,onion
1199,P01_09,P01,19:44.5,19:53.9,cut onion.,cut,onion
1200,P01_09,P01,19:54.6,20:03.9,cut onion.,cut,onion
1201,P01_09,P01,20:00.3,20:14.0,continue cutting onion.,cut,onion
1371,P01_09,P01,30:24.3,30:30.3,cut baking paper,cut,paper:baking
1377,P01_09,P01,30:41.3,30:49.9,cut baking paper,cut,paper:baking
1872,P01_09,P01,58:24.9,58:46.9,cut pizza,cut,pizza
1873,P01_09,P01,58:28.7,58:53.8,cut pizza,cut,pizza